
//prueba de metodo GET para ver listado de usuarios
GET http://127.0.0.1:3000/api/usuarios HTTP/1.1

### para actualizar campo de activo
PATCH http://localhost:3000/api/usuarios/6848c5e726ca5b78f9040758
Content-Type: application/json

{
    "activo": true
}

### para actualizar rol 
PATCH http://localhost:3000/api/usuarios/6848c5e726ca5b78f9040758
Content-Type: application/json

{
    "rol": "empleado"
}

### para crear empleado
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Nuevo Empleado",
  "email": "empleado.nuevo@example.com",
  "password": "passwordSegura123"
}

//prueba de metodo GET para ver listado de usuarios
GET http://127.0.0.1:3000/api/usuarios HTTP/1.1

### para actualizar campo de activo
PATCH http://localhost:3000/api/usuarios/6848c5e726ca5b78f9040758
Content-Type: application/json

{
    "activo": false
}

### para actualizar rol 
PATCH http://localhost:3000/api/usuarios/6848c5e726ca5b78f9040758
Content-Type: application/json

{
    "rol": "empleado"
}