@idUsuario = 6859de68e4bc21342b0d4f9a
@idCerveza = 6856002fdc79cdb7874eb492
@idOtraCerveza = 68586ffaa462f8fca9691588
@idPedido = 685a22fec5a075bb61219575
@idAprobador = 685a1dda89c5a721e9b7d931

### Listar todos los pedidos
GET http://localhost:3000/pedido

### Obtener un pedido por ID
GET http://localhost:3000/pedido/{{idPedido}}

### Listar pedidos por usuario
GET http://localhost:3000/pedido/usuario/{{idUsuario}}

### Crear un nuevo pedido
POST http://localhost:3000/pedido
Content-Type: application/json

{
  "usuario_id": "{{idUsuario}}",
  "cervezas": [
    { "cerveza": "{{idCerveza}}", "cantidad": 3 },
    { "cerveza": "{{idOtraCerveza}}", "cantidad": 4 }
  ]
}

### Actualizar estado y aprobador de un pedido
PATCH http://localhost:3000/pedido/{{idPedido}}
Content-Type: application/json

{
  "aprobado_por": "{{idAprobador}}",
  "estado": "aprobado"
}

### Eliminar un pedido
DELETE http://localhost:3000/pedido/{{idPedido}}