@idUsuario = 684768c24861e333311357da
@idCerveza = 6854ceac38bd69f4c8af6571
@idOtraCerveza = 6854ced238bd69f4c8af6573
@idPedido = 685a22fec5a075bb61219575
@idAprobador = 68477070cb6d86c668efe0ed

### Listar todos los pedidos
GET http://localhost:3000/pedido

### Obtener un pedido por ID
GET http://localhost:3000/pedido/{{idPedido}}

### Crear un nuevo pedido
POST http://localhost:3000/pedido
Content-Type: application/json

{
  "usuario_id": "{{idUsuario}}",
  "cervezas": [
    { "cerveza": "{{idCerveza}}", "cantidad": 5 },
    { "cerveza": "{{idOtraCerveza}}", "cantidad": 2 }
  ]
}

### Actualizar estado y aprobador de un pedido
PATCH http://localhost:3000/pedido/{{idPedido}}
Content-Type: application/json

{
  "aprobado_por": "{{idAprobador}}",
  "estado": "aprobado"
}

### Eliminar un pedido
DELETE http://localhost:3000/pedido/{{idPedido}}