//prueba de metodo GET para ver listado de usuarios
GET http://127.0.0.1:3000/api/usuarios HTTP/1.1

### para actualizar campo de activo
PATCH http://localhost:3000/api/usuarios/6848c5e726ca5b78f9040758
Content-Type: application/json

{
    "activo": false
}

### para actualizar rol 
PATCH http://localhost:3000/api/usuarios/6848c5e726ca5b78f9040758
Content-Type: application/json

{
    "rol": "empleado"
}